pipeline {
    agent any

    stages{
        stage("limpando a workspace"){
            steps{
                sh 'pwd'
                deleteDir()
            }
        }

        stage("Clonando projeto do github"){
            steps{
                git credentialsId: "github-ssh", url: "git@github.com:andremhirai/do25.git"
            }
        }

        stage("Rodar testes unitarios"){
            steps{
                sh "mvn clean test"
            }
        }

        stage("Build do projeto"){
            steps{
                sh "mvn clean package -DskipTests"
            }
        }

        stage("Solicitar autorizacao de deploy"){
            steps{
                script{
                    slackSend(color: "purple", message:"Para aprovar este deploy clique aqui: ${JOB_URL} - [JANELA DE 5 MINUTOS]", channel: "devops-andre")
                    timeout(time: 5, unit: "MINUTES") {
                        input(id: "Deploy Decision", message: "Voce quer aprovar o deploy?", ok: "Deploy")
                    }
                }
            }
        }

        stage(Deploy){
            steps{
                sh 'scp -o StrictHostKeyChecking=no -i /home/vagrant/jenkins target/alura-forum-0.0.1-SNAPSHOT.war vagrant@192.168.1.222:/home/vagrant/alura-forum-0.0.1-SNAPSHOT.war'
                sh "ssh -o StrictHostKeyChecking=no -i /home/vagrant/jenkins vagrant@192.168.1.222 'sudo mv /home/vagrant/alura-forum-0.0.1-SNAPSHOT.war /var/lib/tomcat8/webapps/alura-forum-0.0.1-SNAPSHOT.war'"
            }
        }


    }

}